language: c
compiler: gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libsqlite3-dev libsctp-dev libradiusclient-ng-dev
script: make exclude_modules="db_oracle osp sngtc" all
